Review
nstsvs/stellar-burger pull request #2
Opened 2024-07-23 10:52 UTC by nstsvs

2024-07-25 17:59 UTC, SergeyK2004 requested changes
Очень хорошая работа. 
Тесты написаны аккуратно без лишнего кода. Код приятно читать. При тестировании используются моковые данные, что исключает зависимость от работы сервера, это хорошо.
Есть пара замечаний, которые надо исправить:

https://disk.yandex.ru/d/Ad-yzWNvXX9Wcg Тест не проходит. Проверьте тестирование пользователя.
Так-же посмотрите комментарий в коде.

2024-07-25 17:59 UTC, SergeyK2004 commented on cypress/e2e/constructor.cy.ts
> +    cy.intercept('GET', '/api/auth/user', { fixture: 'user.json' }).as(
**Отлично:**

Использование intercept

2024-07-25 17:59 UTC, SergeyK2004 commented on cypress/e2e/constructor.cy.ts
> +    cy.visit('http://localhost:4000/');
**Можно лучше:**

http://localhost:4000 обычно повторяется несколько раз в коде тестов. Нужно вынести в константу `testUrl`, чтобы можно было одним движением изменить урл для тестов
А можно в документации посмотреть, как настроить быстро `baseUrl` для cypress https://docs.cypress.io/api/commands/visit#Visit-is-automatically-prefixed-with-baseUrl

2024-07-25 17:59 UTC, SergeyK2004 commented on cypress/e2e/constructor.cy.ts
> +    cy.get('[data-cy=bun-bottom]').contains('Краторная булка N-200i (низ)');
**Отлично:**

Отличная проверка действия. Здорово, что проверяете состояние до добавления ингредиента и после.

2024-07-25 17:59 UTC, SergeyK2004 commented on cypress/e2e/constructor.cy.ts
> +    cy.setCookie('refreshToken', 'mock-refresh-token');
**Надо исправить:**

https://disk.yandex.ru/d/Vsj7ucLSHAViVg Согласно задания необходимо очистить хранилище после теста.
После завершения теста принято очищать хранилище и куки, для тогда чтобы эти данные не могли повлиять на прохождение других тестов.

2024-07-25 17:59 UTC, SergeyK2004 commented on src/components/ui/app-header/app-header.tsx
> +              data-cy={'username'}
**Отлично:**

Использование атрибутов для тестирования

2024-07-26 09:26 UTC, nstsvs commented on cypress/e2e/constructor.cy.ts
> +    cy.visit('http://localhost:4000/');
готово, настроила `baseUrl` для cypress

2024-07-26 09:57 UTC, nstsvs commented on cypress/e2e/constructor.cy.ts
> +    cy.setCookie('refreshToken', 'mock-refresh-token');
готово, добавила очистку куки и хранилища в `afterAll`

2024-07-27 04:12 UTC, SergeyK2004 approved these changes
Отличная работа. Поздравляю со сдачей проекта.

2024-08-01 13:37 UTC, merged